image: docker:latest

services:
  - docker:dind

stages:
  - test

variables:
  GO_SRC: src/gitlab.com/$CI_PROJECT_PATH

test:
  stage: test
  image: golang:1.13
  script:
  - go test -count=1 -v ./...
