image: docker:latest

services:
  - docker:dind

stages:
  - build

test:
  stage: build
  image: golang:1.13
  script:
  - go test -count=1 -v ./...

verify:
  stage: build
  script:
    - apk update && apk add git
    - ./verify.sh
  except:
    - master